repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key
  - repo: local
    hooks:
      - id: repo-check
        name: repo check
        entry: npm run check:changed
        language: system
        pass_filenames: false
